### ISSUE TITLE
Extractinator prevents player from joining server

### ISSUE THREAD

**Issue by Somiona** [AlexNijjar/The-Extractinator#3]
```
[Server] [03:02:44] [Server thread/ERROR]: Couldn't place player in world
[Server] java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "$$0" is null
[Server]        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
[Server]        at net.minecraft.network.PacketByteBuf.writeEnumConstant(PacketByteBuf:336) ~[?:?]
[Server]        at com.github.alexnijjar.the_extractinator.TheExtractinator.lambda$onInitialize$0(TheExtractinator.java:59) ~[TheExtractinator-1.0.4.jar:?]
[Server]        at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf:131) ~[?:?]
[Server]        at com.github.alexnijjar.the_extractinator.TheExtractinator.lambda$onInitialize$1(TheExtractinator.java:57) ~[TheExtractinator-1.0.4.jar:?]
[Server]        at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf:131) ~[?:?]
[Server]        at com.github.alexnijjar.the_extractinator.TheExtractinator.lambda$onInitialize$2(TheExtractinator.java:54) ~[TheExtractinator-1.0.4.jar:?]
[Server]        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.0.19+d7c144a865-27ddd48d544c3695.jar:?]
[Server]        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.0.19+d7c144a865-27ddd48d544c3695.jar:?]
[Server]        at net.minecraft.server.PlayerManager.handler$dag000$handlePlayerConnection(PlayerManager:10463) ~[?:?]
[Server]        at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:191) ~[?:?]
[Server]        at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler:130) ~[?:?]
[Server]        at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:117) ~[?:?]
[Server]        at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$dah000$handlePlayerJoin(ServerLoginNetworkHandler:1063) ~[?:?]
[Server]        at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:67) ~[?:?]
[Server]        at net.minecraft.network.ClientConnection.tick(ClientConnection:234) ~[?:?]
[Server]        at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:183) ~[?:?]
[Server]        at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:890) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:324) ~[?:?]
[Server]        at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$bjn000$modifiedRunLoop(MinecraftServer:6856) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Unknown Source) [?:?]
[Server] [03:02:44] [Server thread/INFO]: berrybrownie lost connection: Invalid player data
[Server] [03:02:44] [Server thread/INFO]: berrybrownie left the game
[Server] [03:02:44] [Server thread/WARN]: handleDisconnection() called twice
```

**Comment by AlexNijjar** [comment]
I am not able to replicate this error. I've tried on both a vanilla server and a modded server, and the player is able to join without issue. Could you send a mod list?
