### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Donastria** [AlexNijjar/The-Extractinator#33]
### Bug Description

nice mod that doesn't work worth a bleep! java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extractinator'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoClassDefFoundError: com/teamresourceful/resourcefullib/common/item/tabs/ResourcefulCreativeTab
	at dev.alexnijjar.extractinator.registry.ModItems.<clinit>(ModItems.java:20)
	at dev.alexnijjar.extractinator.Extractinator.init(Extractinator.java:16)
	at dev.alexnijjar.extractinator.fabric.ExtractinatorFabric.onInitialize(ExtractinatorFabric.java:16)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.teamresourceful.resourcefullib.common.item.tabs.ResourcefulCreativeTab
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more
Crashed my game for 2 days before I weeded it out! Fix your mod or take it down! We don't need the headaches!

### How to Reproduce?

just install the broken ass mod and try to load your game. You will crash EVERY SINGLE TIME.

### Expected Behavior

I expected to be able to at least PLAY the game, not fight for two days pulling my hair out on the issue!

### Version

0.2.0

### Mod Loader Version

1.19.4

### Mod Loader

Fabric

### Logs or additional context

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extractinator'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoClassDefFoundError: com/teamresourceful/resourcefullib/common/item/tabs/ResourcefulCreativeTab
	at dev.alexnijjar.extractinator.registry.ModItems.<clinit>(ModItems.java:20)
	at dev.alexnijjar.extractinator.Extractinator.init(Extractinator.java:16)
	at dev.alexnijjar.extractinator.fabric.ExtractinatorFabric.onInitialize(ExtractinatorFabric.java:16)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.teamresourceful.resourcefullib.common.item.tabs.ResourcefulCreativeTab
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more

**Comment by AlexNijjar** [comment]
extractinator requires resourcefullib and resourceful config

https://www.curseforge.com/minecraft/mc-mods/resourceful-lib
https://www.curseforge.com/minecraft/mc-mods/resourceful-config
